[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
from = "/api/*"
to = "https://13.203.227.147/api/:splat"
status = 200
force = true
headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
from = "/ws"
to = "wss://13.203.227.147"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
