[build]
  command = "CI=false npm run build"
  publish = "build"

# Proxy API requests to avoid mixed content issues
[[redirects]]
  from = "/api/*"
  to = "http://13.203.227.147:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
